# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='n_comments',
            field=models.IntegerField(default=0, verbose_name='number of comments'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='n_pingbacks',
            field=models.IntegerField(default=0, verbose_name='number of pingbacks'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
